### PR TITLE
feat: Set volume limit to 250

### PR DESCRIPTION
**Pull request by UsrBinLuna**
### This pull request...
  - [ ] Fixes a bug
  - [ ] Introduces a new feature
  - [x] Improves an existing feature
  - [ ] Boosts code quality or performance

### Description
This PR will higher the volume limit to 250

### Purpose
Why not

### Relevant Issue(s)
N/A

### CODE REVIEW

**Review by oliver194 — APPROVED** [review]
:skrolled2: ok

**Comment by UsrBinLuna** [comment]
merge bitch it has no errors

**Comment by UsrBinLuna** [comment]
close it

**Comment by UsrBinLuna** [comment]
dog-stock-photos-1525793302

**Pull request merged**
